VOCAB = {
    "concept",
    "concept_ancestor",
    "concept_class",
    "concept_relationship",
    "concept_synonym",
    "domain",
    "drug_strength",
    "relationship",
    "vocabulary",
}

CDM531_NON_VOCAB = {
    "care_site",
    "cdm_source",
    "condition_era",
    "condition_occurrence",
    "cost",
    "death",
    "device_exposure",
    "dose_era",
    "drug_era",
    "drug_exposure",
    "fact_relationship",
    "location",
    "measurement",
    "metadata",
    "note",
    "note_nlp",
    "observation",
    "observation_period",
    "payer_plan_period",
    "person",
    "procedure_occurrence",
    "provider",
    "specimen",
    "visit_detail",
    "visit_occurrence",
    "source_to_concept_map",
}

CDM54_NON_VOCAB = {
    "care_site",
    "cdm_source",
    "condition_era",
    "condition_occurrence",
    "cost",
    "death",
    "device_exposure",
    "dose_era",
    "drug_era",
    "drug_exposure",
    "episode",
    "episode_event",
    "fact_relationship",
    "location",
    "measurement",
    "metadata",
    "note",
    "note_nlp",
    "observation",
    "observation_period",
    "payer_plan_period",
    "person",
    "procedure_occurrence",
    "provider",
    "specimen",
    "visit_detail",
    "visit_occurrence",
    "source_to_concept_map",
}

CDM600_NON_VOCAB = {
    "care_site",
    "cdm_source",
    "condition_era",
    "condition_occurrence",
    "cost",
    "device_exposure",
    "dose_era",
    "drug_era",
    "drug_exposure",
    "fact_relationship",
    "location",
    "location_history",
    "measurement",
    "metadata",
    "note",
    "note_nlp",
    "observation",
    "observation_period",
    "payer_plan_period",
    "person",
    "procedure_occurrence",
    "provider",
    "specimen",
    "survey_conduct",
    "visit_detail",
    "visit_occurrence",
    "source_to_concept_map",
}

LEGACY = {
    "cohort",
    "cohort_definition",
    "cohort_attribute",
    "attribute_definition",
}

CUSTOM = {
    "source_to_concept_map_version",
    "stem_table",
}
