name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install nox
        run: pip install nox
      - name: Run ruff linter via nox session
        run: nox -s lint
